with_shirts = ['Myron', 'Matt', 'David', 'Tristan', 'Jim']
without_shirts = ['Brad', 'Dylan', 'Sonju', 'Joe', 'Chris', 'Kate', 'Eric']

with_shirts.pop
without_shirts.pop
with_shirts
without_shirts
with_shirts.push('Jim')
without_shirts.push('Eric')

with_shirts.each do |n|
  puts n
end

without_shirts.each do |n|
  puts n
end



with_shirts = [("Myron","blue","toocool")]


class Test
  def initialize(name, color, coolness)
    @name = name
    @color = color
    @coolness = coolness
  end

  def to_s
    puts "#{@name} + #{@color} + #{@coolness}"
  end

end

test_array = Test.new(with_shirts)
